modLoader="javafml"
loaderVersion="${forge_loader_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/bh679/playermob-mc/issues"

[[mods]]
modId="playermob"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/bh679/playermob-mc"

[[mixins]]
config="playermob.mixins.json"

[[dependencies.playermob]]
    modId="forge"
    mandatory=true
    versionRange="${forge_loader_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.playermob]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.playermob]]
    modId="adventureitemnames"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
